[package]
name = "deadpool"
version = "0.2.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool"
keywords = ["async", "database", "pool"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"
edition = "2018"

[dependencies]
async-trait = "0.1.17"
tokio = "0.2.0-alpha.6"

[workspace]
members = [
    "postgres"
]
