[package]
name = "deadpool"
version = "0.7.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Dead simple async pool"
keywords = ["async", "database", "pool"]
license = "MIT/Apache-2.0"
repository = "https://github.com/bikeshedder/deadpool"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[dependencies]
tokio = { version = "1", features = ["sync", "time"] }
num_cpus = "1.11.1"
# only required when using the `managed` feature
async-trait = { version = "0.1.17", optional = true }
# only required when using the `config` feature
config-crate = { package = "config", version = "0.11", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.3"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }

[workspace]
members = [
    "postgres",
    "lapin",
    "redis",
]
exclude = [
    "examples",
]

[features]
default = ["managed", "unmanaged", "config"]
config = ["config-crate", "serde"]
managed = ["async-trait"]
unmanaged = []

[[bench]]
name = "unmanaged"
harness = false
