[package]
name = "deadpool-example-postgres-actix-web"
version = "0.1.0"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.2.0"
config = "0.10.1"
#deadpool-postgres = { version = "0.5.0", path = "../../postgres" }
deadpool-postgres = "0.5"
dotenv = "0.15.0"
failure = "0.1.6"
serde = { version = "1.0.104", features = ["derive"] }
tokio-postgres = { version = "0.5", features = ["with-uuid-0_8"] }
uuid = { version = "0.8.1", features = ["serde"] }
