[package]
name = "deadpool-example-redis-actix-web"
version = "0.1.0"
authors = ["Tomas Hromada <tomas@hey.com>"]
edition = "2018"

[dependencies]
actix-web = "3.2.0"
deadpool-redis = "0.6.1"
redis = "0.17.0"
